# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# composer dump-env prod

parameters:
    commission_target_currency: '%env(APP_COMISSION_TARGET_CURRENCY)%'
    commission_eu_rate: '%env(float:APP_COMISSION_EU_RATE)%'
    commission_none_eu_rate: '%env(float:APP_COMISSION_NONE_EU_RATE)%'
    
    php_errors_log: true

    container.dumper.inline_factories: true
    
    #app.another_constant: !php/const App\Entity\BlogPost::MAX_ITEMS

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Commission/'
            - '../src/Service/**/ServiceInternal/*'
            - '../src/Kernel.php'
            - '../tests'
    
    App\Service\CurrencyProvider\Providers\CurrencyFreakProvider:
        arguments:
            $http: '@App\Service\HttpRequest\HttpRequestService'
            $cache: '@cache.app'
            $token: '%env(APP_CURRENCY_FREAK_LOOKUP_API_KEY)%'
            $endpoint: '%env(APP_CURRENCY_FREAK_LOOKUP_ENDPOINT)%'
            $baseCurrency: '%env(APP_CURRENCY_FREAK_LOOKUP_BASE_CURRENCY)%'
            $cacheEnabled: '%env(bool:APP_CURRENCY_FREAK_LOOKUP_CACHE)%'
            $cacheKey: '%env(APP_CURRENCY_FREAK_LOOKUP_CACHE_KEY)%'
            $cacheExpireSecond: '%env(int:APP_CURRENCY_FREAK_LOOKUP_CACHE_EXPIRE_SECOND)%'

    App\Service\BinProvider\Providers\BinListProvider:
        arguments:
            $http: '@App\Service\HttpRequest\HttpRequestService'
            $cache: '@cache.app'
            $endpoint: '%env(APP_BIN_LIST_LOOKUP_ENDPOINT)%'
            $cacheEnabled: '%env(bool:APP_BIN_LIST_LOOKUP_CACHE)%'
            $cacheKey: '%env(APP_BIN_LIST_LOOKUP_CACHE_KEY)%'
            $cacheExpireSecond: '%env(int:APP_BIN_LIST_LOOKUP_CACHE_EXPIRE_SECOND)%'

    App\Service\BinProvider\Providers\BinTableProvider:
        arguments:
            $http: '@App\Service\HttpRequest\HttpRequestService'
            $cache: '@cache.app'
            $token: '%env(APP_BIN_TABLE_LOOKUP_API_KEY)%'
            $endpoint: '%env(APP_BIN_TABLE_LOOKUP_ENDPOINT)%'
            $cacheEnabled: '%env(bool:APP_BIN_TABLE_LOOKUP_CACHE)%'
            $cacheKey: '%env(APP_BIN_TABLE_LOOKUP_CACHE_KEY)%'
            $cacheExpireSecond: '%env(int:APP_BIN_TABLE_LOOKUP_CACHE_EXPIRE_SECOND)%'

    App\Service\BinProvider\Providers\BinFakerProvider:
        public: true
    App\Service\CurrencyProvider\Providers\CurrencyFakeProvider:
        public: true