name: Tests

on:
  push:
    branches: ['dev']
    path:
      - .github/run-test.yml
      - src/**
      - tests/**
      - docker/**
      - composer.lock
      - composer.json
      - .dockerignore
  pull_request:
    branches: ['dev']
    path:
      - .github/run-test.yml
      - src/**
      - tests/**
      - docker/**
      - composer.lock
      - composer.json
      - .dockerignore

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker images
      run: export DOCKER_BUILDKIT=1 && docker build -f docker/Dockerfile -t "commission-calculator-test:latest" . --build-arg CURRENCY_FREAK_API=${{ secrets.currency_freak_api }} --build-arg BIN_TABLE_API=${{ secrets.bin_table_api }} --build-arg BIN_CODES_API=${{ secrets.bin_codes_api }}

    - name: Run test
      run: docker run --rm commission-calculator-test:latest
